---
spring:
  profiles: default
server:
  port: 9000
eureka:
  instance:
    hostname: eureka-server
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
---
spring:
  profiles: d1
  application:
    name: eureka-cluster
server:
  port: 9001
eureka:
  instance:
    hostname: eureka-server-c1
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka-server-c2:9002/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
---
spring:
  profiles: d2
  application:
    name: eureka-cluster
server:
  port: 9002
eureka:
  instance:
    hostname: eureka-server-c2
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka-server-c1:9001/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
