---
# Items that apply to ALL profiles:  
spring:
  application:
    name: ABC-SERVICE # ==> This is Service-Id 
eureka:
  instance:
    appname: ABC-SERVICE  # ==> This is a instance of ABC-SERVICE
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30 
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server-c1:9001/eureka
    healthcheck:
      enabled: true
server:
  port: 8000
---
spring:
  profiles: abc-service-replica01
eureka:
  instance:
    appname: ABC-SERVICE  # ==> This is a instance of ABC-SERVICE
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30 
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server-c1:9001/eureka
    healthcheck:
      enabled: true
server:
  port: 8001
---
spring:
  profiles: abc-service-replica02
eureka:
  instance:
    appname: ABC-SERVICE  # ==> This is a instance of ABC-SERVICE
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30 
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server-c1:9001/eureka
    healthcheck:
      enabled: true  
server:
  port: 8002
---
spring:
  profiles: abc-service-replica03
eureka:
  instance:
    appname: ABC-SERVICE  # ==> This is a instance of ABC-SERVICE
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30 
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server-c1:9001/eureka
    healthcheck:
      enabled: true
server:
  port: 8003