kind: Deployment
apiVersion: apps/v1beta1
metadata:
  labels:
    k8s-app: gdsc-eureka-2
  name: gdsc-eureka-2
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gdsc-eureka-2
    spec:
      containers:
      - name: gdsc-eureka-2
        image: 192.168.2.32:5000/eurekaserver:latest
        ports:
        - containerPort: 9011
        env:
          - name: spring.profiles.active
            value: "s2"
          - name: eureka.instance.hostname
            value: "gdsc-eureka-2"
          - name: RSINFOS
            value: "http://gdsc-eureka-1:9010/eurake/"
          - name: server.port
            value: "9011"

---

kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: gdsc-eureka-2
  name: gdsc-eureka-2
  namespace: default
spec:
  type: NodePort
  selector:
    app: gdsc-eureka-2
  ports:
    - protocol: TCP
      port: 9011
      targetPort: 9011
