kind: Deployment
apiVersion: apps/v1beta1
metadata:
  labels:
    k8s-app: gdsc-eureka-1
  name: gdsc-eureka-1
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gdsc-eureka-1
    spec:
      containers:
      - name: gdsc-eureka-1
        image: 192.168.2.32:5000/eurekaserver:latest
        ports:
        - containerPort: 9010
        args: ["--spring.profiles.active=s1","--server.port=9010","--eureka.instance.hostname=gdsc-eureka-1","--RSINFOS=http://gdsc-eureka-2:9011/eurake/"]

---

kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: gdsc-eureka-1
  name: gdsc-eureka-1
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: gdsc-eureka-1
  ports:
    - protocol: TCP
      port: 9010
      targetPort: 9010
