kind: Deployment
apiVersion: apps/v1beta1
metadata:
  labels:
    k8s-app: gdsc-eureka-1
  name: gdsc-eureka-1
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gdsc-eureka-1
    spec:
      containers:
      - name: gdsc-eureka-1
        image: 192.168.2.32:5000/eurekaserver:latest
        ports:
        - containerPort: 9010
        env:
          - name: spring.profiles.active
            value: "s1"
          - name: eureka.instance.hostname
            value: "gdsc-eureka-1"
          - name: RSINFOS
            value: "http://gdsc-eureka-2:9011/eurake/"
          - name: server.port
            value: "9010"
      
---

kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: gdsc-eureka-1
  name: gdsc-eureka-1
  namespace: default
spec:
  type: NodePort
  selector:
    app: gdsc-eureka-1
  ports:
    - protocol: TCP
      port: 9010
      targetPort: 9010
