spring:
  application:
    name: ribbon-service
server:
  port: 8895
ribbon:
  eureka:
   enabled: true
#rb1:
#  ribbon:
#    listOfServers: abc-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server-c1:9001/eureka
    healthcheck:
      enabled: true