spring:
  application:
    name: gateway-service
server:
  port: 8896
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server-c1:9001/eureka
    healthcheck:
      enabled: true
zuul:
  routes:
    abcserver:
      path: /t1/**
      #url: http://localhost:8000/
      serviceId: ABC-SERVICE