spring:
  application:
    name: consumer-hystrix-service
server:
  port: 8898
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server-c1:9002/eureka
    healthcheck:
      enabled: true